models_dir: /models
model_family: vicuna
model_name: 7b
setup_params:
  repo_id: decapoda-research/llama-7b-hf-int4
  filename: llama-7b-4bit.pt
  convert: true
  migrate: false
model_params:
  ctx_size: 2000
  seed: 1337
  n_threads: 8
  n_batch: 2048
