models_dir: /models
model_family: alpaca
model_name: 7b
setup_params:
  repo_id: Sosaka/Alpaca-native-4bit-ggml
  filename: ggml-alpaca-7b-q4.bin
  convert: true
  migrate: false
model_params:
  ctx_size: 2000
  seed: 1337
  n_threads: 8
  n_batch: 2048
